### ISSUE TITLE
Add segment dimming for WPC & GTS3

### ISSUE THREAD

**Issue by toxieainc** [vpinball/pinmame#101]
See https://github.com/vpinball/pinmame/pull/91#issuecomment-1399549232 and the answer to that

**Comment by toxieainc** [comment]
@vbousquet Could this be closed nowadays or is something still missing?

**Comment by vbousquet** [comment]
We now have segment dimming in PinMame for WPC and GTS but there are at least 2 more things that should be addressed:
- the dimming can't be accessed outside PinMame (i.e. libpinmame or vpinmame)
- the eye flicker/fusion is made from a simple low pass filter which has could be improved to get a flatter band. The implementation has a 100Hz slow pulse which causes some slight flickering. For example a 1ms over 5ms PWM gives this:
![image](https://github.com/vpinball/pinmame/assets/2796036/a6be1004-cbd4-43bc-a43d-b3aeab0cdba0)

**Comment by toxieainc** [comment]
Do you have some examples (games/specific sequences) how one could test/improve this in practice?

So (just to double check), the only wired-up way at the moment is the standard/internal (V)PinMAME-window segment rendering, right?
Cause then i would try to improve things a bit, if you're not already on it.

**Comment by vbousquet** [comment]
More informations since thinking about it twice, it needs some more background informations on how to design the filter:
- there is no common wisdom about what is the correct way to do it (I read quite a few scientific papers but didn't find a clear answer),
- most papers state the the eye is supposed to be in fusion mode over 100Hz and in flicker perception below but without a common threshold (I don't think there is one clear limit, and it likely depends on each person),
- this made me select a valid delay for impulse response of 20 to 40ms. 40ms (25Hz) looks like a maximum to me since I think most people will see flicker at this rate,
- the filter was designed for variable rate sampling/filtering (so usual DSP IIR/FIR have to be adjusted for this).
- pulse can be fairly short, so this has to be taken in account (I think the shortest strobing I saw is around 0.5ms)
- maximum bulb integration period is 1ms (it adapts to strobing), which can be considered as stable (constant emission) with regards to over constants above.

**Comment by toxieainc** [comment]
given the amount of knowledge and experiments you gathered already on the topic, i fear i could only add some additional hackery here. ;)

**Comment by vbousquet** [comment]
In the end, this will be a hack, so no problem, feel free to contribute whatever idea you have on this!

**Comment by toxieainc** [comment]
My journey this evening/night into the land of flicker fusion led to much more questions than answers..  :/

As you pointed out, there are a lot of factors coming into play, and some of these are even not known yet when we do the filtering:
- frequency
- intensity/brightness (incl. relative difference to the ambient light)
- color
- local contrast/"edges"
- area
- angle (relative to focus area)
- age,etc of the viewer

So i fear that coming up with some kind of exact model is more or less a dead end. Also, the final output comes into play, too, for us, as one can display with varying output rates (depending on table script, and hardware/monitor setup), so how much flicker/strobing is intended to end up on the user side, and what should we filter/smoothen out instead?

This means that using a low pass with some 'sane' parameters looks exactly like the right tradeoff.

What about a stupid idea though (its already late, so maybe its even extremely stupid, especially as i don't know all the gory details of your PWM changes yet, plus my brain is used to be working in a PCM world ;)):
Could a scheme similar to audio- or image-resampling be used? So to downsample the pulsed data (=converted to PCM first??) to then match the output rate? This would get rid of all flicker that cannot be displayed, but keep frequencies that still fit into the output rate.
This will omit some temporal smoothing of the visual system, but as the output rate is in theory also rather high (>=60Hz), maybe its good enough?
Would be interested to hear your thoughts on this.

**Comment by toxieainc** [comment]
Some more questions regarding the inputs to core_eye_flicker_fusion:

What is the `emission` range? Is this normed to 0..1 and if yes, how is it normed? I.e. are each individual flasher/lamp/LED-types all in the same min..max = 0..1 range? Or is there a global range and the specific min..max depends on the specific type of flasher/lamp/LED? If the first, how could the 'real' brightness range be passed to the function, too?
The reason for this here would be to make the filtering dependent on the actual output intensity (Ferry-Porter law).

`dt` is the 'length' of the emission value that should be integrated/filtered, right? In seconds?

**Comment by vbousquet** [comment]
I agree and came to the same conclusion, we won't be able to simulate everything but still need an acceptable 'hacky' simulation of the flicker fusion effect.

I don't think you can use the output frequency to simulate the flicker-fusion. It obviously depends on which output we are talking about, that is to say low frequency screen vs high frequency hardware controller, but either way, I don't think this would be a good idea:
- screen are too low frequency since 60Hz display is 30Hz blink frequency, so you won't pass the fusion threshold or at least will have high flicker perceived by most people
- when driving high frequency hardware, it seems easier to define a common interface that sends normalized data with a lower data throughput or you would have communication issues => using a simple float defining relative brightness is simpler and more efficient, then the hardware is in charge on driving its output accordingly

The idea I have in mind for the generalized physic output would be to update the external interface of PinMame to something more simple allowing to give access to one *or more* physical characteristics of outputs. For the time being, it fits the existing interface, only for bulbs/VFD/LEDs and only report the main characteristic, that is to say relative brightness, defined as the brightness relative to the brightness of the device running in stable state at its rating level. For example, a classic 44 bulb is rated for 6.3V so the model is supposed to return steady 100% if the bulb is driven steadily with a 6.3V voltage source. One thing, I would like to do later is to also compute and give access to the emission spectrum which would allow to render the change of color of these pulsed bulbs depending on the way they are pulsed (flashers have a clearly visible red/yellow tinting when pulsed at lower PWM duty cycle).

Regarding PCM, I'm not sure I have understood well your idea. What I understand reading you is that you would propose to do a _higher level_ emulation that would read the duty cycle of the PWM, then use this duty cycle in the physic model. This is something I was thinking of doing as well (and in fact did test and have some maths for it). To be clear, by _reading duty cycle_, I mean analyze the hardware, then store the write sequence of a PWM cycle, then compute the PWM ratio from the collected data. For example, for SAM solenoids, you have 48 writes per cycle performed every 250us forming a complete cycle. For SAM inserts, it's another frequency and so on. The big benefit of this is that the duty cycle decoding perform most of the low pass filtering and we will get something that should be really stable with very good performance. But there are also drawbacks:
- this needs to be designed for each output driving logic (so for each hardware, one logic for each output group, also code for each auxiliary board, and so on),
- this needs to be checked against each game as some firmware revision may change the way outputs are driven (that is true for WPC where the lamp driving changed at some point),
- this will be tightly linked to the emulation timings, needing to be readjusted each time we change little things here and there
- this will not handle the filtering needed for other source of modulation than the pure driving logic, or if the modulation is using other logic like dynamic duty cycle variation (not all flip aligned with width modulation, but having counters per output, I don't know if some hardware uses this)
- this will likely be better in terms of performance but how much ? I did profile the current code and in the end all this seems to have very limited CPU impact, beside the fact that the emulation thread is supposed to run on another core than the ones driving VPX for example (I know there is a issue opened on this but it really needs a deeper look since the situation faced by the user tend to push there some qwirck somewhere else like in the B2S data transmission through window registry, bad design table script, or perhaps PinAffinity locking the threads on the wrong cores).

The filter I made is inspired by a classic audio one: it is 4 basic RC filters wired in serial, designed for a 100Hz cut start. The problem is that it is an IIR (infinite impulse response) which is stable but with a fairly high ripple level. A solution would be to use a FIR instead. I did some initial tests on this (I can share it if you want, I have it on some branch somewhere for LED/VFD) but this also seems to have drawbacks: the computing cost is higher and it is more complex to implement for incandescent bulbs (where emission power is very dynamic and not just full on/off like VFD/LED).

`dt` is the length to be integrated in seconds.

**Comment by toxieainc** [comment]
Thanks!

Regarding IIR vs FIR: In `filter.c` there are also some implementations in case you wanna use these, i also have an (unfinished/untested) port lying around to implement Form2 IIRs.

**Comment by toxieainc** [comment]
Some follow up questions to help me understand some more:

What i don't yet get is the logic in
```
const float dt = (now - output->state.bulb.integrationTimestamp) > BULB_INTEGRATION_PERIOD ? BULB_INTEGRATION_PERIOD : (now - output->state.bulb.integrationTimestamp);
 if (dt < BULB_INTEGRATION_PERIOD && !isFlip) // Don't perform too short integration periods unless it is a pulse start/end
  return;
```
Cause from my understanding, clamping dt to BULB_INTEGRATION_PERIOD can falsify the result, or not? Or is this just done to throw away some (weird) outliers where nothing happened for a much longer time? (and so in 99% of the cases the integration length is always a constant otherwise, depending on which lamp/LED/etc the PWM drives? or are there also cases where dt can vary wildly, e.g. for lamps?)

Then i also don't understand why small dt's are allowed on a pulse start. Cause this again can falsify the result, e.g. for the mentioned WOF LEDs the filter cannot distinguish if a BULB_INTEGRATION_PERIOD length of emission 0 came in, or a ~0 length of emission 0. Both will be inserted as 0's into the filter, effectively 'scaling' the PWM duty cycle more towards 0.

Thanks!

**Comment by toxieainc** [comment]
I have some fix(es) for the latter, will let you review them later-on first though.

But i fail to test alphanumeric segment rendering with it. Somehow the core_eye_flicker_fusion codepath is never triggered if i try to test the suggested Surf'n'Safari or BOP. Could you please educate me what i need to enable when testing via PinMAME/PinMAME32?

**Comment by vbousquet** [comment]
The idea of the `isFlip` is to perform integration of full off or full on only. The initial implementation considered linear interpolation of on/off state on very short time frames but it leads to bad results. Integration is really not linear at all, so you need to split the integration on the flip point. That's the intent but the code may have bugs :)

To test, I just add `options.usemodsol |= CORE_MODOUT_ENABLE_PHYSOUT;` to `MACHINE_INIT` of `core.c` (I did add a setting for this but there were conflicts, so I removed it) and it shows in PinMame

**Comment by toxieainc** [comment]
Thanks!
One more question: What is the intention of the `if (pixel[ll][i - 15 + s->cols] < v)` in `if (pixel[ll][i - 15 + s->cols] < v) pixel[ll][i - 15 + s->cols] = v;` ?

**Comment by vbousquet** [comment]
I'm not completely sure about this one. I think it was a max blend between the segments (each segment is defined in an array with a little antialiasing, so when rendered I think we keep the higher value. additive could be right there too). I would need to get back to the code to be sure

**Comment by toxieainc** [comment]
Just a quick note: i'm still heavily experimenting with this.
As you noted, the 4x low pass IIR is really extremely ringing/rippling which becomes apparent at extreme smoothing. Other (simple) filters did not improve the situation much though.  :/
At least there is some additional overall quirkiness with the current implementation that i will be able to fix. But regarding the filtering itself i'm still WIP.

**Comment by toxieainc** [comment]
I think i have a pretty good implementation now for LEDs/VFDs in 08de0a9b38d670c73fdcca39fbce7cbe0827bbab.
SAM LEDs work fine (tiny tiny bit of flicker sometimes though), VFDs show subtle blends/dimmings (e.g. Hoops, Cactus Jacks) while also being rather stable for these displays.

I haven't tested lamps though, as you are the expert there @vbousquet, so please verify if lamps still work (at least) as well as before.
In general, lamps also should need a tweak to the integration loop, similar to my changes, otherwise small Off-States or small integration intervals in general, can falsify the integration significantly, i think. Maybe you have an idea how to do this, otherwise i could also try it if you could provide me with some good testcases/repros. Thanks!

**Comment by toxieainc** [comment]
Something else: I saw that the dmddevice 'interface' doesn't offer per-segment dimming. Is this still worth implementing/exposing or is this old interface going to die soon anyway?

**Comment by toxieainc** [comment]
@vbousquet ping about a repro on how to easily test PWM lamps/flashers, etc, please..  :)
Then i could (hopefully) finish up the improved integration code.

**Comment by vbousquet** [comment]
I don't have a repro for unwanted flicker on bulbs. I played a bit using the latest VPM with your latest change and it looked quite good to me. Perhaps it's already ok (at least it looks fine enough to me, there will always be room for improvment here)

**Comment by toxieainc** [comment]
Still, if you'd have kinda like something that you use for testing, that would be much appreciated. I think a small tweak is still necessary to make the integration cycles more stable, like the change i did for LED/VFDs.

**Comment by vbousquet** [comment]
Made some test to qualify the output. I tested with Monster Basj since it has constant (stable) strobed lamps and I have a real one at a bar near my place, allowing for real world comparisons.

Here is the output of lamp 27 which is constantly strobed when game is started:

![image](https://github.com/vpinball/pinmame/assets/2796036/960b81e2-741d-44b0-87ad-b992ac4fff2a)

It shows a fairly low level of ripples. I will try to have a look to more modern hardware (with shorter strobe period) but I don't think we will face high level of ripple since the bulb physics is already a low pass filter so we are somewhat stacking low pass filters the one on the others.

**Comment by vbousquet** [comment]
Yes, IIR are designed for fix period integration. The way I made it is somewhat abusing it and can be the cause of some of the irregularities

**Comment by volkenborn** [comment]
I just stumbled upon the Birthday greetings for Michelle Eddy on BOP:

![bop_l7](https://github.com/vpinball/pinmame/assets/3236140/99f4aa27-02e8-4e93-84a3-9a1720bf7f65)
![bop_0000](https://github.com/vpinball/pinmame/assets/3236140/fd63c6a2-2472-4944-9314-2aa78c813bd8)
![bop_0001](https://github.com/vpinball/pinmame/assets/3236140/d716376b-522d-4b19-a4d3-69bb2d3ec889)

It's pretty hard to make out as the flicker rate is enourmously high I think.
Would it be possible to lower the time until a segment is lit as opposed to the time it take to dim?
I guess that would be closer to the real looks.

**Comment by toxieainc** [comment]
I just commited (hopefully) the final variant of the integration/fusion code. It's definetly a bit more stable now and less whacky, also the happy birthday message in BOP above is now 'okay' i'd say. It's difficult to mimic the human eye in combo with the segmented display perfectly, so some special cases will always suck, at least until we all use >120Hz HDR monitors and can tweak the code for that.  ;)

Please @vbousquet and @volkenborn test some more if i overlooked something.

**Comment by vbousquet** [comment]
@toxieainc I did some testing and everything looked great to me.

Regarding updating the dmddevice.dll, I think this could be interesting as Freezy's DMD not only provide the physical DMD interface but can also be used for alphanumeric rendering on physical DMD or a very nice alphanumeric segment rendering for virtual display (and as an overlay of B2S). So this would be definitely nice and worth to have it.
