### ISSUE TITLE
Debug build is broken

### ISSUE THREAD

**Issue by droscoe** [vpinball/pinmame#127]
A recent update broke the ability to build in DEBUG.

```
  Assembling asmblit.asm
  Assembling asmtile.asm
ymfm_opm.obj : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Contr
ollerSettings.obj [C:\_dev\github\pinmame\build\vpinmame\Win32\vpinmame.vcxproj]
     Creating library C:/_dev/github/pinmame/build/vpinmame/Win32/Debug/vpinmame.lib and object C:/_dev/github/pinmame/
  build/vpinmame/Win32/Debug/vpinmame.exp
C:\_dev\github\pinmame\build\vpinmame\Win32\Debug\VPinMAME.dll : fatal error LNK1319: 1 mismatches detected [C:\_dev\gi
thub\pinmame\build\vpinmame\Win32\vpinmame.vcxproj]
*** ERROR: ABNORMAL SCRIPT TERMINATION ***
```
I'm looking into it now, but figured I would log it.

**Comment by mjrgh** [comment]
I ran into that as well.  I just deleted the #define from ymfm.h, since it seems like basically a bug that it's there at all.  It was probably added as a hack to get some other build configuration working - the symbol is a Microsoft thing that they put there to make sure you don't forcibly link an incompatible version of the library for your code-gen configuration.  (I think MSFT is actually trying to make our lives easier here - forcing the wrong library would undoubtedly cause run-time corruptions that would cost much more time to track down than this linker error.)

**Comment by droscoe** [comment]
UPDATE:  Looks like the problem is in ymfm.h:
```
+#if defined(_MSC_VER)
+ #define _ITERATOR_DEBUG_LEVEL 0
+#endif
```
 Since this affects debug builds only, I'm not sure why you wouldn't want iterator checks

**Comment by droscoe** [comment]
I commented out those lines and the debug build works again.  Not sure what you want to do long-term, as I don't know what problem this was solving.

**Comment by droscoe** [comment]
> I ran into that as well. I just deleted the #define from ymfm.h, since it seems like basically a bug that it's there at all. It was probably added as a hack to get some other build configuration working - the symbol is a Microsoft thing that they put there to make sure you don't forcibly link an incompatible version of the library for your code-gen configuration. (I think MSFT is actually trying to make our lives easier here - forcing the wrong library would undoubtedly cause run-time corruptions that would cost much more time to track down than this linker error.)

I agree, but its bit more than that.  Setting it to 0 disables iterator bounds checking in debug mode.  I cant imagine you would actually want to do that unless you were building in a third-party library that was messing you up by having it enabled.  This wouldn't even be an issue, if we weren't compiling this stuff in with the main code base.  Ideally, you would have your external dependencies already compiled, and simply link to it (or build them as part of your dependency tree, but as a separate project).  Then you don't incur the tech debt of every included source file.  I really want to clean that part up, but it will mess with a lot of people to do it "right" now.

**Comment by mjrgh** [comment]
> I cant imagine you would actually want to do that unless you were building in a third-party library that was messing you up by having it enabled.

That's what I suspect the issue actually is - when people add this kind of hack, it's almost always because they're trying to work around the linker error they were getting when linking their debug build against some third-party library they were using that was built in release mode.  My guess is that the hack is original equipment from the third-party YMFM code, not something added in PinMame, because PinMame builds fine if you remove it.  It was probably something the original author ran into when trying to link it against some other thing he was testing with and which doesn't apply to PinMame.

**Comment by mjrgh** [comment]
> Ideally, you would have your external dependencies already compiled, and simply link to it (or build them as part of your dependency tree, but as a separate project).

The latter seems better to me - every project I've ever seen that uses the latter ends up with exactly these sorts of ` #define _ITERATOR_DEBUG_LEVEL 0` hacks, because you inevitably get incompatible build configurations.  The Microsoft tools have way too many fun knobs and dials to play with.

**Comment by droscoe** [comment]
@mjrgh are you on Discord?  Would love to pick your brain on something I'm trying to do.  I'm @MrGrynch#1235

**Comment by mjrgh** [comment]
> @mjrgh are you on Discord? 

I'm not, but you reach me by email (it's listed on my github page).

**Comment by toxieainc** [comment]
Actually i added it, but i don't remember why. I started the YMFM port ~a year ago or so but never finished it up then, so i forgot why..
