### ISSUE TITLE
mt_145hb crashes on game start

### ISSUE THREAD

**Issue by toxieainc** [vpinball/pinmame#165]
..while pro and le works.
Maybe related to the LED workarounds??

**Comment by djrobx** [comment]
If send garbage works, then it means metallica inherited newer serial code like Walking Dead LE's  

Walking Dead needs some kind of handshake between the LED controller and the ROM before it will start sending the serial commands.   Older implementations just blasted LED commands to the LED controllers without checking if they're present or not.    Whether it does or doesn't respond correctly, the game eventually ends up sending commands anyway after a bunch of time passes.

The problem is we don't know what response the real machine gives and what the ROM is looking for.   Spamming random garbage just seems to accelerate the process.

**Comment by toxieainc** [comment]
I rather meant the header. I haven't really checked anything so far, i just wired it to the send garbage for now, as the other codepath it will fall in otherwise will make it crash.

**Comment by djrobx** [comment]
I don't even have a working VP setup anymore, not really set up to debug this.    If I could see what the crash was I might be able to help.

**Comment by toxieainc** [comment]
The crash i fixed. I also just checked, the (85 + address, 41, 80) header seems to be also valid for the Boss Edition.
Now i just need to know how you derived https://github.com/vpinball/pinmame/blob/49ca70c39f8e54dbf8d631c96895d824a82fd351/src/wpc/sam.c#L1406

**Comment by djrobx** [comment]
It wasn't anything simple with a straightforward method like finding fast flip addresses.   I was looking at cheat engine to see what things changed before the game finally started sending data.   

The garbage method, if it works, is probably the best way to go.   That was something I figured out after finding metallica's patch addresses, as I was undable to find similar ones that worked for TWD.

**Comment by toxieainc** [comment]
Found it by now, thanks!
