### ISSUE TITLE
White Water ww_lh6 (Flupper) crash on boot

### ISSUE THREAD

**Issue by Jayhay89** [vpinball/pinmame#246]
WW crashes on start up running latest VPinMAME (3.6-880)

**Comment by volkenborn** [comment]
@Jayhay89 Can you please try ww_lh5 instead of ww_l5?
I notice the backbox lamps flicker on L-5 like crazy (old lamp driver code), on LH-5 it's much smoother...
this is probably an effect of the new PWM implementation.

**Comment by francisdb** [comment]
I can confirm the segfault, using `ww_lh6` here

standalone, PINMAME_SHA=e867f6e50e12238e0db658ccc9dde6d19a350c12

**Comment by francisdb** [comment]
```
<unknown> 0x0000000000000000
core_write_pwm_output_8b core.c:2851
parallel_0_out ww.c:529
send_data_to_parallel_output 4094.c:74
HC4094_oe_w 4094.c:168
init_ww ww.c:562
init_machine mame.c:456
run_game mame.c:333
StartGame libpinmame.cpp:643
```

**Comment by vbousquet** [comment]
Yes, I think the problem is that the 4094 are called during initialization causing outputs to be written before there initialization. I will have a look in the evening. There are a few way around this. One of them would be to not use the 4094 emulation which IMHO is overly complicated for the intent. (and in fact, these are not 4094 chips). There are shift registers a bit everywhere in the drivers with fairly simpler implementation, just being triggered on strobe/write (so when emulation has actually started and everyone is properly initialized)

**Comment by volkenborn** [comment]
You may want to check what we did for BOP; it should work the same for WW actually.

**Comment by vbousquet** [comment]
Yes, that's what I was referring to. I have also rewrote all the SAM aux board and lots of them use chained shift registers to send serial data. For me, what you did for BOP is simpler to read/maintain and less bug prone. That's what I would go for. Note that other WPC will likely have the same problem until I propose a fix since I implemented PWM for all WPC aux board last week...

**Comment by volkenborn** [comment]
Fixed it for AFM and WW. I'm not sure about CP, will have a look (this one uses 4 8-bit latches).

**Comment by vbousquet** [comment]
It's correct from the electronic point of view but not from the way mame expects things (at least to my understanding): CPU core are not supposed to perform any emulation (so toggling outputs,..) during initialization. One way to do it is to move the code in the init to the write handler (only keep the HC4094_init in machine init). I think this lead to a somewhat overkill implementation for just a shift register but it will work. The over way is to not use the 4094 'cpu' core and just do the little math of the shift register.

**Comment by volkenborn** [comment]
Yes, see my commit. I removed the 4094 for all games not using it. :)

**Comment by toxieainc** [comment]
> I notice the backbox lamps flicker on L-5 like crazy (old lamp driver code), on LH-5 it's much smoother... this is probably an effect of the new PWM implementation.

Unless i'm testing this wrong, this should be fixed with an upcoming improvement by me for the PWM flicker fusion for lamps.

**Comment by volkenborn** [comment]
Already gone with the switch from 4094 to latches; we need to buffer the writes slightly anyhow so there are no intermittent states showing, which fixed the flicker. 😁
