### ISSUE TITLE
[Question] nvram is not written without Controller.stop routine (?)

### ISSUE THREAD

**Issue by syd711** [vpinball/pinmame#300]
I also asked this the VPX team, but they had no answer, so maybe this question is more related to VPinMAME?

For some tables, e.g. "Checkpoint (Data East)" I realized that the nvram is NOT written when the table exited through PinUP Popper. But a regular exit though VPX does write it. After adding the Controller.Stop method to the script of "Checkpoint", the issue is gone and the nvram is then written too.

What I don't understand: there are other tables like "Create from the black lagoon" which also don't have the "controller.stop" call, but the nvram is written anyway when exited through popper. So what makes tables write the actual nvram file?

**Comment by volkenborn** [comment]
Er, the VPM team is mostly the same, at least if it comes to @toxieainc and myself... 😀

**Comment by syd711** [comment]
Ah, then I hope I did not generate too much spam here -  wasn't aware of that.

**Comment by toxieainc** [comment]
All good. Its better to track things where they belong.

My 2 cents so far: The 'official way' so that its only stored when the controller is stopped is actually the way to go. If its stored otherwise, too, i would consider it a nice sideeffect.  ;)

But lets find out what exactly differs and if we could improve things for other machines, too.

**Comment by syd711** [comment]
Sounds good, let me know if you need more information.

**Comment by syd711** [comment]
Let's close this ticket since Francis already delivered answers in the VPX ticket, sorry again for the duplicate post.
