### ISSUE TITLE
Use of GTS3 & WPC driver through dmdevice can not be correct for both DMD rendering / frame identification

### ISSUE THREAD

**Issue by Panasony1008** [vpinball/pinmame#344]
Confirmed with Waterworld PuPPack.
PupCapture triggers barely work on the latest master. (VPinMAME-sc-3.6.0-1118)
It triggers without any problems in the pre-release version v3.6.0-998.

**Comment by Panasony1008** [comment]
PUPCapture is a trigger mechanism for PuPPack.
Most tables that use PinMame control PuP with this trigger.
In other words, if something changes in the DMD output and the image no longer matches, you will no longer be able to control PuP.
See this page for more details.
https://www.nailbuster.com/wikipinup/doku.php?id=pup_capture

**Comment by vbousquet** [comment]
The change in PinMame were made knowing this and some care to avoid this type of issue, by splitting the DMD output in 2 streams: one for frame identification, expected to be backward compatible, and one for rendering which performs the PWM integration. As much as possible, everything has been kept backward compatible with colorization and pup but your report let think that not everything is.

The thing is that while doing that I also fixed a few bugs, especially for the following hardwares:
- Sega/Stern Whitestar and DataEast 128x32 had wrong timings (this can impact pup/colorization as frames are now delivered at the correct speed)
- GTS3 had wrong timings (this can impact pup/colorization as frames are now delivered at the correct speed)
- WPC had wrong overall shading in some situations (game code can switch from 2 to 3 frame shading, but this should not impact pup/colorization)
These were bugs that have been solved but can cause issue with things relying on these bugs to be present and that are not there anymore.

Could you be more precise on which pup (or colorization) are not working anymore ? It is only Waterworld or are there others ?

**Comment by Panasony1008** [comment]
If the trigger didn't work at all it would be obvious, but since it only works partially it's difficult to detect.
Waterworld is the only I've noticed so far.
Up to VPinMAME-sc-3.6.0-1050 it seems to be normal.

**Comment by vbousquet** [comment]
I have re-implemented the same behavior as pre-PWM build for better backward compatibility. I tested it with colorization files and it did work well. @Panasony1008 could you give a try to the latest version and check that everything is back to normal ?

**Comment by Panasony1008** [comment]
I have confirmed that WaterWorld PuP works with VPinMAME-sc-3.6.0-1121.
I was able to confirm that PuP triggers normally.
However, when using WaterWorld, the external DMD flickers abnormally.

**Comment by vbousquet** [comment]
Yeah, that was to be expected since external dmddevice.dll only takes one stream for both pup/colorization and rendering.

I fear there is no easy backward compatible way for GTS3, since the driver used to be hacked to get somewhat okish (but still wrong) shades by hacking the frequencies (breaking timings and animation speed).

For the time being, the streams are like this:
- render frames => sent to VPX through VPM/Controller
- identify frames => sent to dmddevice for colorization/pup backward compatibility, but leading to wrong rendering (only the timing fixes are applied on this stream, not the other bug fixes for GTS3, WPC,...).
- both render/identify frames => sent to the upcoming global state exchange to solve it all.

What I would propose to go forward would be:
- update dmddevice.dll interface by adding a single new function that would receive both stream to allow dmddevice implementors to update, using the right stream for the right use,
- choose which stream we want in the legacy interface between render/identify (My preference would go for render stream).

Obviously, the sad thing is that, in the end, all dmddevice users will have to update either way, but this is needed to get correct DMD rendering.

@toxieainc What do you think ?

**Comment by toxieainc** [comment]
Sounds good to me.. Thanks!

**Comment by Panasony1008** [comment]
Just to confirm, the fix in 3.6.0-1127 means that Waterworld PuPPack triggers are no longer triggering as they were in the previous bugged version.
Is this intentional?

**Comment by vbousquet** [comment]
> Just to confirm, the fix in 3.6.0-1127 means that Waterworld PuPPack triggers are no longer triggering as they were in the previous bugged version. Is this intentional?

Yes it is. GTS3 game will need an update of dmddevice.dll to support colorization/pinup events again. Other hardwares should be good
