### ISSUE TITLE
CSI lamps react weird

### ISSUE THREAD

**Issue by toxieainc** [vpinball/pinmame#351]
Most prominently the 'C''S''I' lamps in the return lanes (happens on both the Javier table and the September LED MOD).
Also i got it multiple times that CSI and WPT dropped 2 balls from the trough. Tested with VPX 10.7.4 and 10.8.0 and 10.8.1, along with current PinMAME (https://github.com/vpinball/pinmame/commit/7398e23eabdecd069f4f8bc47a2a9a42746019c9).

**Comment by toxieainc** [comment]
@vbousquet

**Comment by vbousquet** [comment]
Regarding the CSI lamps, I tested with the Javier version. On my side, when ball passes on the lane, it lights up with a little blink. It seems fair to the real table (compared with PAPA video here: https://www.youtube.com/watch?v=1jhtK0PoCm0) as the return lanes have slow fade in/fade out on the real table so at some point, they are likely just around the on/off threshold for old tables not implementing the PWM stuff. On SAM hardware, all lights are derived from the PWM implementation, since everything is faded, but this may lead to this type of flicker. A way to improve could be to use a 2 state integrator (like for solenoids, which use a latency based integrator) instead of the bulb model when PWM is not requested by the client. Not sure if this is really needed/worth though. What do you think ?

**Comment by toxieainc** [comment]
No clue. If its 'simple enough' it may be worth it so that older tables still work similar to before, but its your decision, you're the expert there.

**Comment by vbousquet** [comment]
It was very basic, so I added it directly. Looks good to me.

**Comment by toxieainc** [comment]
Great, thanks!!
