### ISSUE TITLE
hypbl_l6 / Hyperball - missing segments

### ISSUE THREAD

**Issue by francisdb** [vpinball/pinmame#380]
PINMAME_SHA = 0eb9fb596ec2f24e1fd3b6cd3cbaae09ea10836e

Hyperball (Williams 1981)

This is what it looks like in the pinmame dmd/physical dmd

(switched Controller.hidden = 0 in the table)

dmd rendered by vpinball standalone

[Screencast From 2024-11-29 15-02-42.webm](https://github.com/user-attachments/assets/cc9362d6-7747-42ea-bb63-6726897b7ea4)

**Comment by francisdb** [comment]
Would be great if somebody could confirm this on windows

**Comment by francisdb** [comment]
Looks like a mixup between 7 and 10-segment displays

**Comment by Karl030167** [comment]
On Windows with VPX 10.8 rc5, vpinmame v1127 ,all in x64 , No such error

**Comment by francisdb** [comment]
Maybe this should be reported in libdmdutil then @jsm174 ?

**Comment by volkenborn** [comment]
There is a commented line in core.c:

		case GEN_S7:
			//CORE_SEGLAYOUT_2x7Num_4x1Num_1x16Alpha;		//!! hmm i did this for a reason??

This would be the Hyperball layout. Is there something missing here maybe? 😉

**Comment by francisdb** [comment]
Introduced here https://github.com/vpinball/pinmame/commit/d42e078ee55543217e638f18113d6849045feb9d#diff-a134e35b957da240a0287ca823ff72b9c809102c1d7b4f590330af6f94dd3527R890

by @vbousquet

**Comment by francisdb** [comment]
Not sure I understand what you mean

That code is at least 8 years old
https://github.com/vpinball/pinmame/blame/546a4f83c882a31065342daf252f0d505f03e3d8/src/wpc/dmddevice.cpp

**Comment by volkenborn** [comment]
This would mean that there never was a valid definition for Hyperball then?

**Comment by jsm174** [comment]
along time ago, @toxieainc added support for alphanumerics to be rendered to a raw dmd buffer. (I feel like around tournament logic work)

libpinmame then got to leverage that for free, and presents a new a new dmd style to vpx standalone, `CORE_DMDSEG`.

https://github.com/vpinball/pinmame/blob/78e8b9fc33973585b56834fb9d6903f9bd46520b/src/wpc/core.c#L1248-L1252

How that dmd is generated is right above it:

https://github.com/vpinball/pinmame/blob/78e8b9fc33973585b56834fb9d6903f9bd46520b/src/wpc/core.c#L1218-L1237
 
So from your screen shot, this is that buffer:

![Screenshot 2024-12-03 at 7 35 15 AM](https://github.com/user-attachments/assets/5ad3bf0c-8cc5-4fee-a4e5-de1cadb10eb0)

This is the table script rendering based on segment data it pulls from libpinmame:

![Screenshot 2024-12-03 at 7 35 52 AM](https://github.com/user-attachments/assets/48022425-d305-40dc-970d-538a56e3f290)

So the fix is definitely in pinmame, not libdmdutil. 

Maybe the `hmm i did this for a reason??` needs to look at the rom name like some of the other hardware gens?

https://github.com/vpinball/pinmame/blob/78e8b9fc33973585b56834fb9d6903f9bd46520b/src/wpc/core.c#L887-L901

**Comment by volkenborn** [comment]
Yes, I think a check for "hypbl", 5 should actually do it here. The define is already in. I should mention there are only 1x12Alpha digits used on Hyperball.

**Comment by toxieainc** [comment]
@francisdb Please verify, thanks all!

**Comment by jsm174** [comment]
@toxieainc - I'll have to make a new build of vpx with this pinmame sha before @francisdb can test.. let me do that now.

**Comment by francisdb** [comment]
![image](https://github.com/user-attachments/assets/54929cdc-86c4-43fa-9e4d-e912b8fa9b6c)

Confirmed fixed

**Comment by toxieainc** [comment]
Thanks guys!
