### ISSUE TITLE
AC/DC lights very intense

### ISSUE THREAD

**Issue by Dicentim974** [vpinball/pinmame#399]
Hi,
I've noticed an issue with latest versions ov Vpinmame.
Lights are very blurry.
All gets back to normal when switching back on v3.6.0-1122-79a301d pre-release.
By the way thanks for having fixed flippers DOF issues.
![thumbnail (1)](https://github.com/user-attachments/assets/23de3a69-fb8c-4cc6-a062-734a25fa823c)

**Comment by vbousquet** [comment]
This is a table bug : AC/DC's GI used to be wrong (missing full emulation). It is now correctly emulated. The table has a hack around this that need to be removed

**Comment by Dicentim974** [comment]
> This is a table bug : AC/DC's GI used to be wrong (missing full emulation). It is now correctly emulated. The table has a hack around this that need to be removed

Hi, Thanks for your answer. I removed any vbs file in script, redownloaded the table but still the same. What do you mean by "hack" ?

**Comment by Nicals** [comment]
Something was wrong on the visual pinball side. To make their table work, vpx did something to compensate this bug.

But the "wrong" thing in visual pinball was fixed, so we now have something on the table compensating for something that does not exist anymore.
What they were telling you [here](https://vpuniverse.com/files/file/12471-acdc-luci-stern-2013-vpw-mod/?do=findComment&comment=81738) is that they need to remove their correction since it is no longer relevant.

**Comment by Rkade80s** [comment]
It's not just the ACDC table. It's a lot of other tables. I've been setting the bloom to zero on them, but it only helps a little bit. It seems the problem started after switching from 3.5 to 3.6.
